version: "3.9"

services:

# docker mariadb
  mariadb:
    build: ./mariadb/
    image: "mariadbf"
    container_name: "maria1"
    environment:
      - MARIADB_ROOT_PASSWORD=root 
    networks:
      FreezerNetwork:
        ipv4_address: 172.18.0.6

# docker jenkins
#  jenkins:
#   build: ./jenkins/
#   image: "jenkinsfreezer"
#   networks:
#     FreezerNetwork:
#       ipv4_address: 172.18.0.2
#   depends_on:
#     - "Agent"

#docker agent
#  agent:
#    build: ./agent/
#    container_name: "agent1"
#    image: "agentf"
#    networks:
#      FreezerNetwork:
#        ipv4_address: 172.18.0.3

# docker proftpd
  proftpd:
    build: ./proftpd/
    container_name: "proftpd1"
    image: "proftpdf"
    networks:
      FreezerNetwork:
        ipv4_address: 172.18.0.4

# docker nginx
  nginx:
    build: ./nginx/ 
    container_name: "nginx1"  
    image: "nginxf"
    ports:
      - "80:80"
      - "443:443"
    networks:
      FreezerNetwork:
        ipv4_address: 172.18.0.5
    depends_on:
      - "mariadb"
      - "proftpd"
      - "agent"

# définition du réseau
networks:
  FreezerNetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
