version: "3.9"

services:

# docker mariadb
  mariadb:
    build: ./maria/
    image: "mariadb"
    container_name: "maria1"
    environment:
      - MARIADB_ROOT_PASSWORD=root
    networks:
      FreezerNetwork:
        ipv4_address: 172.18.0.6


# docker jenkins
  jenkins:
    build: ./jenkins/
    container_name: "jenkins1"
    image: "jenkins"
    networks:
      FreezerNetwork:
        ipv4_address: 172.18.0.2
    depends_on:
      - "Agent"

# docker agent
  agent:
    build: ./agent/
    container_name: "agent1"
    image: "agent"
    networks:
      FreezerNetwork:
        ipv4_address: 172.18.0.3

# docker proftpd
  proftpd :
    build: ./proftpd/
    container_name: "proftpd1"
    image: "pro"
    networks:
      FreezerNetwork:
        ipv4_address: 172.18.0.4

# docker nginx
  nginx :
    build: ./nginx/
    container_name: "nginx1"
    image: "nginx"
    ports:
      - "80:80"
      - "443:443"
    networks:
      FreezerNetwork:
        ipv4_address: 172.18.0.5
    depends_on:
      - "mariadb"
      - "proftpd"
      - "jenkins"
      - "agent"

# définition du réseau
networks:
  FreezerNetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
